FROM fluent/fluent-bit:latest@sha256:5d504081f0dab3ae19d8d41babee637bf43ace874cb8b8426046a226b556539b

COPY fluent-bit.conf /fluent-bit/etc/fluent-bit.conf
COPY parsers.conf /fluent-bit/etc/parsers.conf
